version: '3.8'

services:
  slack-bot:
    build: .
    container_name: kl-slack
    env_file:
      - .env
    environment:
      - SLACK_SERVICE_TOKEN
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

